Repository p2p-org/p2p-wallet-ios, pull requests merged in 2022-08, with the labels that each got.

#379 [Draft] Migrate to new TKey
  Podfile.lock
  p2p_wallet/Info.plist
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/UIKit/SwiftUI/UIKit/TextButtonView.swift
Labels: onboarding

#384 [PWN-4436] Feature/pwn 4436 notification toast
  Podfile.lock
  p2p_wallet/AppDelegate.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInAccountHasBeenUsed/SocialSignInAccountHasBeenUsedViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInTryAgain/SocialSignInTryAgainViewModel.swift
  p2p_wallet/Services/NotificationsService/NotificationService.swift
Labels: onboarding

#368 feat: move navigating logic from viewmodel to coordinator
  Podfile.lock
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
Labels: onboarding

#387 [PWN-4410] Fix/pwn 4410 Suppress error on auth cancellation
  Podfile.lock
  p2p_wallet/Services/Auth/SocialService/AppleSocialService.swift
  p2p_wallet/Services/Auth/SocialService/GoogleSocialService.swift
Labels: onboarding

#386 [PWN-4249] Feature/pwn 4249 processing phone
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewController.swift
Labels: onboarding

#388 [PWN-4436] Snackbar update
  Podfile.lock
Labels: onboarding

#389 [PWN-4414] Fix/pwn 4414 reachability
  Podfile
  Podfile.lock
  p2p_wallet/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Extensions/Combine/Reachability+Combine.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Services/NotificationsService/NotificationService.swift
Labels: onboarding

#393 [PWN-4534] On the country selection screen, the search results are displayed incorrectly
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: bug

#390 [PWN-4533] When the country selection screen opens, the search must be active
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInViewModel.swift
Labels: bug

#354 [PWN-4316] Do not search for a name with direct address
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.ViewModel.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/RecipientsCollectionView/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientsListViewModel.swift
Labels: send

#358 [PWN-4367] Skip the step of creating a username (old flow)
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.ExplanationVC.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.ViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWallet.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.ViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWallet.swift
Labels: onboarding

#399 Removed global reachability check
  p2p_wallet/AppCoordinator/AppCoordinator.swift
Labels: onboarding

#401 [PWN-4551] Fixed backbutton issue
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: onboarding

#405 [PWN-4545] Need to remove the click effect via waiting for a response
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSelection/SocialSignInView.swift
Labels: onboarding

#404 [PWN-4550] [PWN-4556]
  p2p_wallet/Resources/Base.lproj/LaunchScreen.storyboard
  p2p_wallet/UIKit/SwiftUI/BottomActionContainerStyle.swift
Labels: onboarding

#410 [PWN-4530] On the country selection screen, the currently selected country should be displayed at the top of the list
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
Labels: bug

#414 UI Fixes for OTP
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: onboarding

#412 API Gateway Implementation
  p2p_wallet/Info.plist
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: onboarding

#406 [PWN-4555] Fix/pwn 4555 design fix
  p2p_wallet/Resources/Base.lproj/Localizable.strings
Labels: onboarding

#418 OTP UI fixes
  Podfile.lock
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: onboarding

#421 [PWN-4650] Unknown country error
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: onboarding

#420 [PWN-4642] Reset pincode after failure
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeSnackbar.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
Labels: bug

#437 [PWN-4612] Left and right margins to the "?" button and the “back” arrow are different on all screens
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/Base.lproj/Localizable.stringsdict
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.stringsdict
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestoreScreen.swift
Labels: bug, onboarding

#436 [PWN-4766] PWN-4766: The “Continue“ button does not appear correctly via going to the code entry screen/returning back
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
Labels: onboarding

#435 [PWN-4777] PWN-4777: After selecting a country the flag of another country with the same code is displayed on the number entry screen
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: onboarding

#433 [PWN-4772] PWN-4772: Countries should be sorted alphabetically, not in order of country codes when searching
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift
Labels: onboarding

#432 [PWN-4758] PWN-4758: The countries at the end of the list are hidden behind the keyboard on the search country screen
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
Labels: onboarding

#426 [PWN-4371] PhoneNumber and OTP errors
  Podfile.lock
  p2p_wallet/Resources/Assets.xcassets/rocket.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/rocket.imageset/Object=Fast  and Free@2x.png
  p2p_wallet/Resources/Assets.xcassets/rocket.imageset/Object=Fast  and Free@3x.png
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/Base.lproj/Localizable.stringsdict
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.stringsdict
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialAuthService/AuthServiceBridge.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestoreScreen.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.Cache.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.Cell.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.ListViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.ViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivablePaths/NewDerivablePaths.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivablePaths/NewDerivablePaths.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewRestoreWallet.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewRestoreWallet.ViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewRestoreWallet.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Screen/OnboardingBlockScreen.swift
  p2p_wallet/UIKit/SwiftUI/TextButtonView.swift
Labels: onboarding

#438 Seed Phrase UI fixes
  Podfile.lock
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivableAccounts.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewDerivableAccounts/NewDerivablePaths/NewDerivablePaths.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreWallet/NewRestoreWallet.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
  p2p_wallet/UIKit/Views/WLCard.swift
Labels: onboarding

#440 [NO-TASK] Refactoring seed flow in a separate coordinator
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreSeedPhraseDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
Labels: onboarding, refactor

#441 [PWN-4756] Changing the flow of creating a pin and biometrics
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/ProtectionLevel/ProtectionLevelView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/ProtectionLevel/ProtectionLevelViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreScreen.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/Views/ICloudWalletCell.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/RestoreICloudDelegatedCoordinator.swift
Labels: onboarding
