Repository p2p-org/p2p-wallet-ios, pull requests merged in 2022-11, with the labels that each got.

#673 [PWN-5784] Use onPressed with button design component
  p2p_wallet/Scenes/Main/History/History.ErrorView.swift
  p2p_wallet/Scenes/Main/History/Transaction/View/TransactionView.swift
  p2p_wallet/Scenes/Main/ProcessTransaction/Status/ProcessTransaction.Status.ViewController.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTC.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTCFree.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+TopUp.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2.ConfirmSwapping.RootView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
Labels: bug

#675 [PWN-5789] Update question mark tint color
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift
Labels: bug

#678 [PWN-5788] Update alert button, error view constraints and some icons…
  p2p_wallet/Extensions/UIViewController+Extensions.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/History/History.ErrorView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift
  p2p_wallet/UIKit/Views/UIView+Builders.swift
  p2p_wallet/UIKit/Views/WLNavigationBar.swift
Labels: bug

#671 [PWN-5765] Update design component color
  p2p_wallet/Extensions/UIViewController+Extensions.swift
  p2p_wallet/Resources/Assets.xcassets/button-paste.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar-highlighted.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar-highlighted.imageset/Icon.png
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar-highlighted.imageset/Icon@2x.png
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar-highlighted.imageset/Icon@3x.png
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar.imageset/Icon.png
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar.imageset/Icon@2x.png
  p2p_wallet/Resources/Assets.xcassets/empty-user-avatar.imageset/Icon@3x.png
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/History/History.ErrorView.swift
  p2p_wallet/Scenes/Main/History/Transaction/View/TransactionView.swift
  p2p_wallet/Scenes/Main/ProcessTransaction/Status/ProcessTransaction.Status.ViewController.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTC.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+CreateRenBTCFree.swift
  p2p_wallet/Scenes/Main/ReceiveToken/NetworkSelection/ConfirmReceivingBitcoin/ConfirmReceivingBitcoin.ViewController+TopUp.swift
  p2p_wallet/Scenes/Main/ReceiveToken/ReceiveToken.ViewController.swift
  p2p_wallet/Scenes/Main/ReceiveToken/Views/ReceiveToken.QrCodeCard.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/SendToken.ChooseRecipientAndNetwork.SelectAddress.RootView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/SendToken.ChooseRecipientAndNetwork.SelectAddress.RecipientView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseRecipientAndNetwork/SelectAddress/Subviews/SendToken.ChooseRecipientAndNetwork.SelectAddress.TitleView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/ChooseTokenAndAmount/SendToken.ChooseTokenAndAmount.RootView.swift
  p2p_wallet/Scenes/Main/SendToken/Subscenes/Confirm/SendToken.ConfirmViewController.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/ConfirmSwapping/OrcaSwapV2.ConfirmSwapping.RootView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.MainSwapView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift
  p2p_wallet/UIKit/Views/UIView+Builders.swift
  p2p_wallet/UIKit/Views/WLNavigationBar.swift
Labels: keyapp

#683 [PWN-5847] Duplicates in hidden tokens on HomeView
  p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/View/HomeWithTokensView.swift
  p2p_wallet/Scenes/Main/NewHome/HomeWithTokens/ViewModel/HomeWithTokensViewModel.swift
Labels: bug

#684 [PWN-5850] Add snack bar in creation wallet on Pin code screen
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
Labels: onboarding

#702 [PWN-5909] Swap keyboard fix
  Podfile.lock
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/OrcaSwapV2.RootView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.MainSwapView.swift
  p2p_wallet/Scenes/Main/SwapToken/OrcaSwapV2/Subviews/OrcaSwapV2.WalletView.swift
Labels: bug

#689 [PWN-5787] Open history from push without opening intercom
  p2p_wallet/Scenes/Main/Main.ViewController.swift
  p2p_wallet/Services/Networking/Endpoint.swift
Labels: bug, Main Screen 1.1

#718 [PWN-5959] Fix iOS 14 SwiftUI issues with observable object
  p2p_wallet/Extensions/Combine/BaseViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInAccountHasBeenUsed/SocialSignInAccountHasBeenUsedViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
  p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialViewModel.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
  p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift
Labels: bug

#720 [PWN-5958] Connect to socket only from iOS 15
  p2p_wallet/Extensions/Combine/BaseViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInAccountHasBeenUsed/SocialSignInAccountHasBeenUsedViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
  p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialViewModel.swift
  p2p_wallet/Scenes/Main/Main.ViewModel.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
  p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift
  p2p_wallet/Services/Socket.swift
Labels: bug

#714 [PWN-5965] Migrate to default currency if it is not USD
  p2p_wallet/AppDelegate.swift
Labels: bug

#707 [PWN-5833] Add Torus Restore loader
  Podfile
  Podfile.lock
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Resources/walletAnimation.json
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/OnboardingNavigationController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInWait/SocialSignInWaitViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
Labels: onboarding

#693 [PWN-5852] Update insets for action button on restore with seed phrase screen
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
Labels: onboarding

#692 [PWN-5853] Change button appearance on Create Username screen
  p2p_wallet/Coordinators/TabBar/SettingsCoordinator.swift
  p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameCoordinator.swift
  p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameView.swift
  p2p_wallet/Scenes/Username/CreateUsername/CreateUsernameViewModel.swift
  p2p_wallet/Scenes/Username/CreateUsername/Models/CreateUsernameParameters.swift
Labels: onboarding

#366 [PWN-4419] feat: refactor getAvailableWalletsToPayFee
  p2p_wallet/Services/SendService/SendService.swift
Labels: refactor
