Repository p2p-org/p2p-wallet-ios, pull requests merged in 2022-09, with the labels that each got.

#454 [PWN-4612] Left and right margins to the "?" button and the “back” arrow are different on all screens
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
Labels: bug, onboarding

#453 [PWN-4750] Need to remove the old pin code entry screen from the creation wallet scenario
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
Labels: bug, onboarding

#451 [NO-TASK] OnboardingStateMachineProvider to create tKeyFacade and apiGatewayClient
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/StateMachineProvider/OnboardingStateMachineProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
Labels: onboarding, refactor

#456 [PWN-4889] [PWN-4891]
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionViewModel.swift
Labels: bug, onboarding

#459 [PWN-4912][PWN-4879] Toasts are too low in PincodeViewController, Keyboard animation fix
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
Labels: bug, onboarding

#458 [PWN-4911] Start screen is flickering when create switching to restore wallet
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/Result/RestoreResultViewController.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartView.swift
  p2p_wallet/UIKit/SwiftUI/PageView/PagingView.swift
Labels: bug, onboarding

#461 [NO-TASK] Add device share to debug menu
  p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletViewModel.swift
  p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift
  p2p_wallet/Scenes/DebugMenu/ViewModel/DebugMenuViewModel.swift
Labels: enhancement, onboarding

#462 [PWN-4899] PWN-4899: Seed phrase details screen ui bugs + Add RecoveryKit to New Settings
  p2p_wallet/Coordinators/TabBar/SettingsCoordinator.swift
  p2p_wallet/Extensions/View+Extensions.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/NewSettings/Settings/View/SettingsView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
Labels: onboarding

#464 [PWN-4901] Slider "Show my seed phrase" bugs
  p2p_wallet/Models/AuthenticationPresentationStyle.swift
  p2p_wallet/Scenes/Main/Main.ViewController.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeChangeStartView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailViewModel.swift
Labels: bug

#469 [PWN-4750] Need to remove the old pin code entry screen from the creation wallet scenario
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
Labels: onboarding

#472 [PWN-4980] [PWN-4981] [PWN-4969] States when shares don't match or exist
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
Labels: bug, onboarding

#487 [PWN-4962] Remove disable state from onboarding screens
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialSelection/SocialSignInView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocialOption/RestoreSocialOptionView.swift
Labels: onboarding

#486 [PWN-4974] Restore flow titles
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
Labels: onboarding

#484 [PWN-4910] Correct seed phrase error string
  Podfile.lock
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletViewModel.swift
  p2p_wallet/Services/Defaults.swift
Labels: bug, onboarding

#471 [PWN-4899] PWN-4899 && PWN-4900
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift
Labels: onboarding

#489 [PWN-4911] Apply new tKey API
  Podfile.lock
  p2p_wallet/Info.plist
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/StateMachineProvider/OnboardingStateMachineProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift
  p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift
Labels: onboarding

#488 [PWN-5063] New enter phone behaviour
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Services/TransactionHandler/TransactionHandler+Extensions.swift
Labels: onboarding

#491 [PWN-4989] Start screen is blinking while opening the main screen
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
Labels: bug, onboarding

#493 [PWN-4850] Update phone number error handling in create and restore scenarios
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
Labels: onboarding

#494 [PWN-4955] Validate create wallet lastState
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BaseOTPViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingService.swift
Labels: bug, onboarding

#495 [PWN-5154] [PWN-5155] Remove fallback button for biometrics check
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/Main/Settings/Settings.ViewModel.swift
Labels: bug, onboarding

#496 [PWN-5119] Make restore as a start screen if device share is available
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/StartOnboardingNavigationProvider.swift
Labels: onboarding

#498 [PWN-4900] Seed phrase details - your seed phrase screen ui bugs
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
Labels: onboarding

#499 [PWN-5150] Add biometry check on iCloud restore. Refactoring of coordinatorIO
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreScreen.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/RestoreICloudDelegatedCoordinator.swift
Labels: bug, onboarding

#500 [PWN-5180] Move navigaiton controller settings to a single onboarding…
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/OnboardingNavigationController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
Labels: bug, onboarding

#503 [PWN-5191] Add email as separate label with scaling modifiers. OnboardingContentData
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/UIKit/SwiftUI/OnboardingContentView/OnboardingContentData.swift
  p2p_wallet/UIKit/SwiftUI/OnboardingContentView/OnboardingContentView.swift
Labels: onboarding

#502 [PWN-4841] Change logic of iCloud restore if only one account is stored
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/ICloud/BaseICloudRestoreViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreViewModel.swift
Labels: bug, onboarding

#516 [PWN-5123] Fire timer immediately
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: bug, onboarding

#511 [PWN-4841] Fix infinite loader if biometry is failed
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
Labels: bug, onboarding

#522 [PWN-5062] [PWN-5228] [PWN-5229] [PWN-5230] [PWN-5231] Fix/pin UI fixes
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/ForgetPinView.swift
  p2p_wallet/Services/PinService.swift
Labels: onboarding

#523 [PWN-5239] Fix/pwn 5239
  Podfile.lock
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: onboarding

#521 [PWN-5003] Update texts
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/BiometricsAuthProvider.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/Pincode/PincodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionButtonFactory.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/ICloudRestore/ICloudRestoreScreen.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/SeedPhraseRestore/SeedPhraseRestoreWalletView.swift
  p2p_wallet/Scenes/Main/Authentication/Authentication.PincodeViewController.swift
  p2p_wallet/Scenes/Main/Authentication/Authentication.ViewController.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/View/SettingsView.swift
  p2p_wallet/Scenes/Main/Settings/Settings.ViewController.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/ForgetPinView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeChangeCoordinator.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeVerifyView.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/SeedPhraseDetail/SeedPhraseDetailView.swift
  p2p_wallet/Scenes/StartOnboarding/Continue/ContinueCoordinator.swift
Labels: onboarding

#509 [PWN-4640] Add intercom in the flow of creating and restoring
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/RestoreWalletCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ICloudRestore/RestoreICloudDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreSeedPhraseDelegatedCoordinator.swift
Labels: onboarding

#526 [PWN-5250] Info button on OnboardingBlockScreen
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Screen/OnboardingBlockScreen.swift
Labels: bug, onboarding

#528 [PWN-4640] Added Intercom
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/Pincode/SecuritySetupDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/Main/Main.ViewController.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeChangeCoordinator.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/PincodeVerifyView.swift
Labels: onboarding

#527 [PWN-5003] Update texts on Onboarding
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/BindingPhoneNumberDelegatedCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/SocialSignIn/SocialSignInDelegatedCoordiantor.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Screen/OnboardingBrokenScreen.swift
Labels: onboarding

#513 [PWN-4809] Positive balance mark
  p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift
  p2p_wallet/Analytics/AmplitudeEvent/AmplitudeIdentifier.swift
  p2p_wallet/Scenes/Main/NewHome/Home/ViewModel/HomeViewModel.swift
Labels: analytic

#534 [PWN-5222] Onboarding analytics
  p2p_wallet/Analytics/AmplitudeEvent/AmplitudeEvent.swift
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/ChooseRestoreOption/ChooseRestoreOptionViewModel.swift
  p2p_wallet/Scenes/StartOnboarding/Start/StartViewModel.swift
Labels: onboarding

#533 [PWN-5261] Open enter phone instead of enter otp while continuing cre…
  p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingService.swift
Labels: bug, onboarding

#532 [PWN-5249] feat: readable deviceName
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/Main/Settings/Subscenes/RecoveryKit/RecoveryKitView.swift
  p2p_wallet/Services/Device.swift
Labels: onboarding

#531 [PWN-5003] Update error screen texts if device and social shares not …
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreCustom/RestoreCustomDelegateCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
Labels: onboarding

#530 [PWN-5230] feat: fix Panel's height
  p2p_wallet/Scenes/Main/Settings/Subscenes/PincodeChange/ForgetPinView.swift
Labels: onboarding

#539 [PWN-5269] Open keyboard if OTP code is incorrect
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
Labels: bug, onboarding

#538 [PWN-4790] Need to implement a scenario of moving from error screens with timer to the start and continue screens
  Podfile.lock
  p2p_wallet/Scenes/StartOnboarding/Start/StartCoordinator.swift
Labels: onboarding

#541 [PWN-5191] Put email at any position inside OnboardingContentView at any position
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/RestoreSocial/RestoreSocialDelegatedCoordinator.swift
  p2p_wallet/UIKit/SwiftUI/OnboardingContentView/OnboardingContentData.swift
  p2p_wallet/UIKit/SwiftUI/OnboardingContentView/OnboardingContentView.swift
Labels: onboarding

#543 Remove JWT lib
  Podfile
  Podfile.lock
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialAuthService/AuthServiceBridge.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/Common/SocialAuthService/JWTTokenValidator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/CreateWalletViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
  p2p_wallet/Services/Auth/SocialService/AppleSocialService.swift
  p2p_wallet/Services/GlobalWebView.swift
Labels: onboarding

#546 Consider test environment as release, not debug
  p2p_wallet/Scenes/CreateOrRestoreWallet/OnboardingConfig.swift
  p2p_wallet/Services/Auth/SocialService/SocialService.swift
  p2p_wallet/Services/Environment.swift
Labels: bug, onboarding

#535 [PWN-5078] Implement solend banner
  p2p_wallet/Extensions/SwiftUI/FixedList.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/InvestSolend/Banner/InvestSolendBannerCenter.swift
  p2p_wallet/Scenes/Main/InvestSolend/Banner/InvestSolendBannerCenterViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/Banner/View/InvestSolendBannerView.swift
  p2p_wallet/Scenes/Main/InvestSolend/Banner/ViewModel/InvestSolendBannerViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/InvestSolendView.swift
  p2p_wallet/Scenes/Main/InvestSolend/InvestSolendViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialView.swift
  p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialViewModel.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
  p2p_wallet/Services/Defaults.swift
Labels: solend

#548 [PWN-5006] Шторки выбора токенов депозита/снятия
  p2p_wallet/Coordinators/SolendTokenActionCoordinator.swift
  p2p_wallet/Coordinators/SolendTransactionDetailsCoordinator.swift
  p2p_wallet/Extensions/Double+Extensions.swift
  p2p_wallet/Resources/Assets.xcassets/closeAction.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/closeAction.imageset/Cross.pdf
  p2p_wallet/Resources/Assets.xcassets/feeInfo.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/feeInfo.imageset/Info.pdf
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/.DS_Store
  p2p_wallet/Scenes/Main/.DS_Store
  p2p_wallet/Scenes/Main/InvestSolend/Deposit/DepositSolendViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/InvestSolendViewModel.swift
  p2p_wallet/Scenes/Main/InvestSolend/SolendTransactionDetails/SolendTransactionDetailsView.swift
  p2p_wallet/Scenes/Main/InvestSolend/TokenToDeposit/View/TokenToDepositView.swift
  p2p_wallet/Scenes/Main/InvestSolend/TokenToWithdraw/View/TokenToWithdrawView.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
Labels: solend
