Repository p2p-org/p2p-wallet-ios, pull requests merged in 2023-07, with the labels that each got.

#1429 [PWN-9120] Put correct phone number if there is none on first entry to striga
  Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
Labels: bug

#1430 [PWN-9049] Handle timer from the first time if it was zero. Make it nil as default
  p2p_wallet/Common/Services/Defaults.swift
  p2p_wallet/Common/Services/Storage/UserWalletManager.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
Labels: bug

#1437 [PWN-8863] Do not select place of birth from info bottom sheet
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
Labels: bug

#1442 [PWN-9049] Handle resend request only once
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
  p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: bug

#1450 [PWN-8912] Change setup of address country on second striga registration
  p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
Labels: bug

#1447 [PWN-9032] Handle internet connection error on 2 striga screens
  p2p_wallet/Common/Extensions/NSError+Extensions.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
Labels: bug

#1452 [PWN-8912] Remember lastChosenCountry on second registration step for…
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
Labels: bug

#1453 [PWN-9032] Display no connection error on start of striga otp
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
Labels: bug

#1455 [PWN-9167] Do not close banner on special kyc statuses
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
Labels: bug

#1456 [PWN-9235] Use current value and error while work with fetching state
  Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift
Labels: bug

#1457 [PWN-9213] Send tap subject check after reload of bank transfer
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
Labels: bug

#1460 [PWN-9249] Fix home small banner view
  p2p_wallet/Resources/Assets.xcassets/kyc-finish.imageset/Frame.pdf
  p2p_wallet/Scenes/Main/NewHome/Subview/Banners/HomeSmallBannerView.swift
Labels: bug

#1389 [PWN-8423] Remove source parameter if sendFlow parameters is presented
  p2p_wallet/Common/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift
  p2p_wallet/Common/Services/ClipboardManager.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Actions/ActionsCoordinator.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/Receive/ReceiveView.swift
  p2p_wallet/Scenes/Main/Receive/ReceiveViewModel.swift
  p2p_wallet/Scenes/Main/Sell/Pending/SellPendingCoordinator.swift
  p2p_wallet/Scenes/Main/Sell/SellCoordinator.swift
  p2p_wallet/Scenes/Main/Sell/SellSOLInfoSheet/SellSOLInfoCoordinator.swift
  p2p_wallet/Scenes/Main/Send/Empty/SendEmptyCoordinator.swift
  p2p_wallet/Scenes/Main/Send/Input/SendInputCoordinator.swift
  p2p_wallet/Scenes/Main/Send/Input/SendInputView.swift
  p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
  p2p_wallet/Scenes/Main/Send/Models/SendTransaction.swift
  p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
  p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
  p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkCoordinator.swift
  p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
  p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusView.swift
  p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
  p2p_wallet/Scenes/Main/TransactionDetailView/TransactionDetailViewModel.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsCoordinator.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsViewModel.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/Subview/WormholeSendFeesViewModel.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
  p2p_wallet/Scenes/TabBar/TabBarViewModel.swift
  p2p_wallet/Scenes/Web3Auth/Onboarding/CreateWallet/CreateWalletCoordinator.swift
  p2p_wallet/Scenes/Web3Auth/Onboarding/RestoreWallet/RestoreWalletCoordinator.swift
Labels: send, analytic

#1463 [PWN-9213] Fix banner tap processing logic
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/Empty/HomeEmptyViewModel.swift
  p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
Labels: bug

#1487 Fix min amount from 1 to 10 EUR
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
Labels: bug

#1488 [PWN-9256] Fix decimals length for USDC
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorView.swift
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
Labels: bug

#1489 [PWN-9256] Fixes for validation logic and error handling (stop timer …
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorView.swift
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
Labels: bug

#1493 [PWN-9330] Handle empty response
  p2p_wallet/Scenes/Main/BankTransfer/WithdrawCalculator/WithdrawCalculatorViewModel.swift
Labels: bug

#1515 [PWN-9436] Start timer once transaction is called
  p2p_wallet/Scenes/Main/BankTransfer/Claim/BankTransferClaimCoordinator.swift
Labels: bug

#1520 [PWN-9440] Return Network error if request is failed due to connection
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Extensions/NSError+Extensions.swift
  Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferOutgoingUserActionConsumer.swift
  Packages/KeyAppKit/Sources/BankTransfer/UserAction/StrigaBankTransferUserActionConsumer.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/UserAction/UserActionError.swift
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/BankTransferRenderableAccount.swift
  p2p_wallet/UI/SwiftUI/Renderable/FinanceBlockView.swift
Labels: bug

#1514 [PWN-9234] Fixes for release
  Packages/KeyAppKit/Sources/KeyAppBusiness/Ethereum/EthereumTokenService+DataCorrection.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/Ethereum/EthereumTokenService.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/Price/PriceService.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/UserAction/SynchronizedDatabase.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/UserAction/UserActionConsumer.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/UserAction/UserActionService.swift
  Packages/KeyAppKit/Sources/Send/Wormhole/UserAction/WormholeSendUserActionConsumer.swift
  Packages/KeyAppKit/Sources/Wormhole/Claim/WormholeClaimUserActionConsumer.swift
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemView.swift
  p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/Aggregator/CryptoEthereumAccountsAggregator.swift
  p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountCellView.swift
  p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountsView.swift
  p2p_wallet/Scenes/Main/Crypto/Components/Crypto Accounts/CryptoAccountsViewModel.swift
  p2p_wallet/Scenes/Main/Crypto/Container/CryptoCoordinator.swift
  p2p_wallet/Scenes/Main/Crypto/Container/CryptoViewModel.swift
  p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Service/HomeAccountsSynchronisationService.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/RendableAccount+SolanaAccount.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/RenderableAccount.swift
  p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/Subviews/ChooseSwapTokenItemView.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
  p2p_wallet/Scenes/TabBar/TabBarViewModel.swift
Labels: auto:qa-deploy
