Repository p2p-org/p2p-wallet-ios, pull requests merged in 2023-06, with the labels that each got.

#1323 [PWN-8447] List selection screens
  Packages/KeyAppKit/Sources/BankTransfer/Mock/MockStrigaLocalProvider.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaCreateUserRequest.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaSourceOfFunds.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaUserDetailsResponse.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Models/StrigaUserIndustry.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/BankTransfer/CountryChoose/ChooseCountryService.swift
  p2p_wallet/Scenes/Main/BankTransfer/CountryChoose/Country+ChooseItemRenderable.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/ChooseIndustry/ChooseIndustryDataLocalProvider.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/ChooseIndustry/ChooseIndustryService.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/ChooseIndustry/Industry.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/ChooseSourceOfFunds/ChooseSourceOfFundsService.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/ChooseSourceOfFunds/StrigaSourceOfFunds+Extensions.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemService.swift
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemView.swift
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift
  p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/Service/ChooseSwapTokenService.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/ChooseWormholeSend/ChooseWormholeTokenService.swift
  p2p_wallet/SwiftUI/Renderable/EmojiTitleCellView.swift
  p2p_wallet/SwiftUI/Renderable/TitleCellView.swift
Labels: no-qa

#1325 Feature/pwn 8736
  Packages/KeyAppKit/Sources/BankTransfer/Models/UserData.swift
  Packages/KeyAppKit/Sources/Onboarding/Common/ResendCounter.swift
  Packages/KeyAppKit/Sources/Onboarding/Utils.swift
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
  p2p_wallet/Resources/Assets.xcassets/thumbsup-image.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/thumbsup-image.imageset/Fingerprint@2x.png
  p2p_wallet/Resources/Assets.xcassets/thumbsup-image.imageset/Fingerprint@3x.png
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoView.swift
  p2p_wallet/Scenes/Main/BankTransfer/Info/BankTransferInfoViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/KYC/KYCCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaTransfer/StrigaTransferCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaTransfer/StrigaTransferView.swift
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCompletedView.swift
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
  p2p_wallet/Scenes/Main/Topup/Actions/TopupActionsViewModel.swift
  p2p_wallet/Services/Defaults.swift
  p2p_wallet/Services/Storage/UserWalletManager.swift
Labels: no-qa

#1338 [PWN-8786] Fix balance update when view is disappeared
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: bug

#1327 [PWN-8645] feat(web3auth): metadata storage
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator.swift
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitView.swift
  p2p_wallet/Scenes/Main/NewSettings/Subscenes/RecoveryKit/RecoveryKitViewModel.swift
  p2p_wallet/Services/Storage/KeychainStorage.swift
  p2p_wallet/Services/Storage/WalletMetadataProvider.swift
  p2p_wallet/Services/Storage/WalletMetadataService.swift
Labels: no-qa

#1350 feat: update iso31661-alpha3 code for countries
  Packages/KeyAppKit/Sources/CountriesAPI/Models.swift
  Packages/KeyAppKit/Sources/CountriesAPI/Resources/countries.json
  Packages/KeyAppKit/Tests/UnitTests/BankTransferTests/StrigaEndpointTests.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
Labels: no-qa

#1361 Bugfix/striga registration
  p2p_wallet/Extensions/Date+Extensions.swift
  p2p_wallet/Extensions/String+Extensions.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
Labels: bug

#1363 [PWN-8848] LogoutService
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaLocalProvider.swift
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/NewSettings/Subscenes/PincodeChange/ForgetPinView.swift
  p2p_wallet/Services/Auth/Logout/LogoutService.swift
Labels: bug, no-qa

#1369 [PWN-8812] [PWN-8813] Fix field validation errors for striga registra…
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDetailedButton.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
Labels: bug

#1358 feat: change deployment target to iOS 15
  Packages/KeyAppKit/Package.swift
  Packages/KeyAppKit/Sources/KeyAppNetworking/Extensions/URLSession+Extensions.swift
  Packages/KeyAppKit/Sources/Moonpay/Provider/Moonpay.Provider.swift
  Packages/KeyAppKit/Sources/NameService/NameServiceImpl.swift
  Packages/KeyAppKit/Sources/NameService/URLSession+Extension.swift
  Packages/KeyAppKit/Sources/Sell/Sell+Moonpay/Moonpay.Provider+Extensions.swift
  Packages/KeyAppKit/Sources/SolanaPricesAPIs/URLSession+Extension.swift
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Coordinators/AppCoordinator/AppCoordinator+AppEventHandlerDelegate.swift
  p2p_wallet/Extensions/Combine/Publisher+asyncMap.swift
  p2p_wallet/Extensions/String+AmountFormat.swift
  p2p_wallet/Extensions/SwiftUI/FixedList.swift
  p2p_wallet/Extensions/UINavigationController+Extensions.swift
  p2p_wallet/Extensions/UITextField+Combine.swift
  p2p_wallet/Extensions/View+Extensions.swift
  p2p_wallet/Scenes/DebugMenu/View/DebugMenuView.swift
  p2p_wallet/Scenes/Main/InvestSolend/Tutorial/SolendTutorialView.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsView.swift
  p2p_wallet/Scenes/SelectCountry/View/SelectCountryView.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
  p2p_wallet/Services/ImageSaver.swift
  p2p_wallet/Services/Logger/LogManagerLoggers/AlertLogger/AlertLogger.swift
  p2p_wallet/Services/Networking/HttpClient.swift
  p2p_wallet/Services/Networking/URLSession+Extensions.swift
  p2p_wallet/SwiftUI/List/WrappedList.swift
  p2p_wallet/SwiftUI/Wrappers/WrapperForSearchingView.swift
  project.yml
Labels: no-qa

#1388 [PWN-8967] Feature/pwn 8967 timestamp interger
  Packages/KeyAppKit/Sources/Onboarding/Common/Models/WalletMetaData.swift
Labels: no-qa

#1390 [PWN-8968] Show phoneNumber for first time if user is already registered
  Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferServiceImpl.swift
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/StrigaBankTransferUserDataRepository.swift
Labels: bug

#1377 Allow newTextButton not to have maxWidth
  Packages/KeyAppUI/Sources/KeyAppUI/Button/TextButton/New/NewTextButton.swift
Labels: UI

#1411 [PWN-9049] Update timer for OTP request on the previous registration …
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterSMSCode/EnterSMSCodeViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/otp/StrigaOTPCoordinator.swift
Labels: bug

#1415 [PWN-8949] Update textfields focus states. Handle next and done buttons
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Models/StrigaRegistrationField.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/SecondStep/StrigaRegistrationSecondStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDateTextField.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationPhoneTextField.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationSectionView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
Labels: bug

#1426 [PWN-8970] Handle Resend SMS error
  Packages/KeyAppKit/Sources/BankTransfer/Striga/Repository/DataProviders/StrigaRemoteProviderImpl.swift
Labels: bug

#1424 [PWN-9118] feat: re-calculate the amountTo after removing failed routes
  p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift
  p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/JupiterSwapBusinessLogic.swift
  p2p_wallet/Scenes/Main/Swap/State/JupiterSwapState.swift
Labels: no-qa
