Repository p2p-org/p2p-wallet-ios, pull requests merged in 2023-05, with the labels that each got.

#1185 [PWN-8202] Rewrite ChoosePhoneCode and DerivableAccounts view from UIKit to SwiftUI
  p2p_wallet/Extensions/UITextField+Combine.swift
  p2p_wallet/Models/DerivableAccount.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeCoordinator.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeItemView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/ChoosePhoneCodeViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/PhoneCodeCell.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/PhoneCodeCellSeparatorView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/ChoosePhoneCode/SelectableCountry.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/DerivableAccountsCache.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/DerivableAccountsView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/DerivableAccountsViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/SelectDerivableType/SelectDerivableType.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/SelectDerivableType/SelectDerivableType.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/SelectDerivableType/WLBottomSheet_Deprecated/DimmingPresentationController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/SelectDerivableType/WLBottomSheet_Deprecated/FlexibleHeightPresentationController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/SelectDerivableType/WLBottomSheet_Deprecated/WLBottomSheet_Deprecated.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/Subviews/DerivableAccountsCardView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/DerivableAccounts/Subviews/DerivableAccountsItemView.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/BaseCollectionView_Deprecated/BaseCollectionViewCell.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.Cache.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.Cell.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.ListViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.ViewController.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.ViewModel.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/NewDerivableAccounts.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/NewDerivableAccounts/WLCard.swift
  p2p_wallet/Scenes/CreateOrRestoreWallet/RestoreWallet/Steps/SeedPhraseRestore/RestoreSeedPhraseDelegatedCoordinator.swift
  project.yml
Labels: refactor

#1208 [PWN-8274] Display no digits after dot if value is zero
  Packages/KeyAppKit/Sources/KeyAppKitCore/Blockchain/CurrencyFormatter.swift
Labels: bug

#1212 [PWN-8275] Update solana-swift dependency
  Packages/KeyAppKit/Package.resolved
  Packages/KeyAppKit/Package.swift
Labels: bug

#1195 [PWN-8185] If price is not retrieved, do not display fiat amount on c…
  p2p_wallet/Scenes/Main/History/New/Model/RendableListTransactionItem+Mock.swift
  p2p_wallet/Scenes/Main/History/New/Subview/HistoryItemView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ClaimSentViaLinkTransaction.swift
  p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift
Labels: bug

#1234 [PWN-8396] Hide max button if it shouldn't be available
  p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputView.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
Labels: bug

#1231 [PWN-8416] Feature/pwn 8416 swap error logger
  Podfile.lock
  p2p_wallet/Info.plist
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Scenes/Main/NewSettings/Settings/ViewModel/SettingsViewModel.swift
  p2p_wallet/Scenes/Main/Swap/Common/Models/JupiterSwapTransaction.swift
  p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Logger.swift
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
  p2p_wallet/Services/AppInfo.swift
  p2p_wallet/Services/SwapErrorLogger/SwapErrorDetail.swift
  p2p_wallet/Services/SwapErrorLogger/SwapErrorLogger.swift
  p2p_wallet/Services/SwapErrorLogger/SwapErrorLoggerError.swift
Labels: auto:qa-deploy

#1224 [PWN-8332] Do not update data from background threads on ChooseItem s…
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift
Labels: bug

#1219 [PWN-8326] Fix wrong formation of whole numbers
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: bug

#1220 [PWN-8264] Remove reschedule update on every state change
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: bug

#1217 [PWN-8265] Do not display largeTitle on Swap screens
  p2p_wallet/Scenes/Main/Swap/Swap/JupiterSwapCoordinator.swift
Labels: bug, UI

#1240 [PWN-8403] Replace "5-20 seconds" with "few seconds" in Send bottomsheet
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/Send/TransactionStatus/SendTransactionStatusViewModel.swift
  p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+UserAction.swift
Labels: UI

#1242 [PWN-8531] Log analytic event for swap approve button
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: bug

#1250 [PWN-8586] Update PhoneNumberKit dependency
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  project.yml
Labels: bug

#1258 [PWN-8332] Do not call update user wallets every time view is appeare…
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift
  p2p_wallet/Scenes/Main/Swap/Swap/SwapView.swift
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: bug

#1293 [PWN-8439] Striga. Create integration with Create User Method
  Packages/KeyAppKit/Sources/BankTransfer/Models/RegistrationData.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/StrigaBankTransferService.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/StrigaMockBankTransferService.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/IStrigaProvider.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/Models/CreateUserRequest.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/Models/CreateUserResponse.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/StrigaEndpoint.swift
  Packages/KeyAppKit/Sources/BankTransfer/StrigaProvider/StrigaProvider.swift
Labels: no-qa

#1298 [PWN-8446] First step
  Packages/KeyAppKit/Sources/BankTransfer/Models/RegistrationData.swift
  Packages/KeyAppKit/Sources/BankTransfer/Repository/BankTransferUserDataRepository.swift
  Packages/KeyAppKit/Sources/BankTransfer/Repository/Providers/StrigaBankTransferLocalProvider.swift
  Packages/KeyAppKit/Sources/BankTransfer/Repository/StrigaBankTransferUserDataRepository.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/BankTransferService.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/StrigaBankTransferService.swift
  Packages/KeyAppKit/Sources/BankTransfer/Service/StrigaMockBankTransferService.swift
  Packages/KeyAppUI/Sources/KeyAppUI/Generated/Asset+Generated.swift
  Packages/KeyAppUI/Sources/KeyAppUI/Resources/Colors.xcassets/Sea.colorset/Contents.json
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/Colors.xcassets/lightSea.colorset/Contents.json
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/BankTransfer/BankTransferCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/BankTransferInfoViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/CountryChoose/ChooseCountryService.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepCoordinator.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepViewModel.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDateTextField.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationInformerView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
  p2p_wallet/Scenes/Main/InvestSolend/SolendTransactionDetails/SolendTransactionDetailsView.swift
  p2p_wallet/SwiftUI/List/ListBackgroundModifier.swift
  p2p_wallet/SwiftUI/Spinner/Spinner.swift
Labels: no-qa

#1305 [PWN-8446] Small ui fixes
  p2p_wallet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/FirstStep/StrigaRegistrationFirstStepView.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationDateTextField.swift
  p2p_wallet/Scenes/Main/BankTransfer/StrigaRegistration/Subviews/StrigaRegistrationTextField.swift
Labels: no-qa

#1303 Remove deprecated code
  p2p_wallet/Scenes/CreateOrRestoreWallet/CreateWallet/Steps/EnterPhoneNumber/EnterPhoneNumberViewModel.swift
Labels: bug
