Repository p2p-org/p2p-wallet-ios, pull requests merged in 2023-04, with the labels that each got.

#1120 [PWN-7089] Feature/pwn 7089 bug fixes
  Podfile.lock
  p2p_wallet/AppDelegate.swift
  p2p_wallet/Coordinators/TabBar/ActionsCoordinator.swift
  p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
  p2p_wallet/Extensions/UIApplication+Extensions.swift
  p2p_wallet/Info.plist
  p2p_wallet/Resources/AppDelegate/AppDelegateProxyService.swift
  p2p_wallet/Resources/AppDelegate/AppflyerAppDelegateService.swift
  p2p_wallet/Resources/AppDelegate/DeeplinkAppDelegateService.swift
  p2p_wallet/Resources/Assets.xcassets/app-icon-square.imageset/167.png
  p2p_wallet/Resources/Assets.xcassets/app-icon-square.imageset/40 1.png
  p2p_wallet/Resources/Assets.xcassets/app-icon-square.imageset/80.png
  p2p_wallet/Resources/Assets.xcassets/app-icon-square.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/connectionErrorCat.imageset/Contents.json
  p2p_wallet/Resources/Assets.xcassets/connectionErrorCat.imageset/failed.png
  p2p_wallet/Resources/Assets.xcassets/connectionErrorCat.imageset/failed@2x.png
  p2p_wallet/Resources/Assets.xcassets/connectionErrorCat.imageset/failed@3x.png
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/RxSwift_Deprecated/PendingTransaction.swift
  p2p_wallet/Scenes/Main/History/New/HistoryView.swift
  p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
  p2p_wallet/Scenes/Main/History/New/Model/RendableListTransactionItem+PendingTransaction.swift
  p2p_wallet/Scenes/Main/History/New/NewHistoryCoordinator.swift
  p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkActivityItemSource.swift
  p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkHistoryCoordinator.swift
  p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkHistoryView.swift
  p2p_wallet/Scenes/Main/History/New/SentViaLink/SentViaLinkTransactionDetailView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/Coordinator/ReceiveFundsViaLinkCoordinator.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/View/LinkErrorView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/View/LinkWasClaimedView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/View/ReceiveFundsViaLinkView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/View/SendViaLinkClaimErrorView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift
  p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
  p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
  p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchViewModel.swift
  p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkCoordinator.swift
  p2p_wallet/Scenes/Main/Send/SendViaLink/SendCreateLinkErrorView.swift
  p2p_wallet/Scenes/Main/Send/SendViaLink/SendLinkCreatedView.swift
  p2p_wallet/Scenes/Main/Send/SendViaLink/SendLinkCreatedViewModel.swift
  p2p_wallet/Scenes/Main/Send/SendСoordinator.swift
  p2p_wallet/Scenes/Main/Swap/State/BusinessLogic/Helpers/JupiterSwapBusinessLogic+Calculate.swift
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
  p2p_wallet/Scenes/Main/TransactionDetailView/Model/RendableDetailTransaction+PendingTransaction.swift
  p2p_wallet/Scenes/TabBar/TabBarController.swift
  p2p_wallet/Scenes/TabBar/TabBarViewModel.swift
  p2p_wallet/Services/AnalyticsManager/Events/KeyAppAnalyticsEvent.swift
  p2p_wallet/Services/AnalyticsManager/Providers/AppsFlyer/AppsFlyerAnalyticsProvider.swift
  p2p_wallet/Services/AuthenticationHandler.swift
  p2p_wallet/Services/SendViaLinkStorage/SendViaLinkStorage.swift
  p2p_wallet/Services/SendViaLinkStorage/SendViaLinkTransactionInfo.swift
  p2p_wallet/UIKit/Transitions/BottomSheet/DimmPresentationController.swift
  p2p_wallet/UIKit/Transitions/BottomSheet/PanelTransition.swift
  p2p_wallet/UIKit/Transitions/BottomSheet/PresentationController.swift
Labels: auto:qa-deploy

#1130 [PWN-7798] Support AnyPublishers data update on ChooseItem Screen
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemService.swift
  p2p_wallet/Scenes/Main/Common/ChooseItem/ChooseItemViewModel.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift
  p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/Service/ChooseSwapTokenService.swift
  p2p_wallet/Scenes/Main/Wormhole/ChooseWormholeSend/ChooseWormholeTokenService.swift
Labels: refactor

#1079 [PWN-7466] Fix unit tests for Wormhole and KeyAppKit modules. Add som…
  Packages/KeyAppKit/Tests/UnitTests/KeyAppBusinessTests/Helper/MockSolanaAPIClientBase.swift
  Packages/KeyAppKit/Tests/UnitTests/WormholeTests/BundleCodingTests.swift
  Packages/KeyAppKit/Tests/UnitTests/WormholeTests/EthereumPrivateKeyTests.swift
Labels: bug

#1110 [PWN-7830] Load history from the init
  p2p_wallet/Scenes/Main/History/New/HistoryViewModel.swift
Labels: bug

#1145 [PWN-7089] Feature/pwn 7089 bug fixes 2
  .github/workflows/build-test.yml
  Podfile.lock
  p2p_wallet/Resources/AppDelegate/AppDelegate+Injection.swift
  p2p_wallet/Resources/AppDelegate/AppflyerAppDelegateService.swift
  p2p_wallet/Resources/AppDelegate/DeeplinkAppDelegateService.swift
  p2p_wallet/Resources/Base.lproj/Localizable.strings
  p2p_wallet/Resources/en.lproj/Localizable.strings
  p2p_wallet/Resources/fr.lproj/Localizable.strings
  p2p_wallet/Resources/ru.lproj/Localizable.strings
  p2p_wallet/Resources/vi.lproj/Localizable.strings
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/View/ReceiveFundsViaLinkView.swift
  p2p_wallet/Scenes/Main/ReceiveFundsViaLink/ViewModel/ReceiveFundsViaLinkViewModel.swift
  p2p_wallet/Scenes/Main/Send/Input/SendInputViewModel.swift
  p2p_wallet/Scenes/Main/Send/RecipentSearch/RecipientSearchView.swift
  p2p_wallet/Scenes/Main/Swap/Swap/SwapViewModel.swift
Labels: auto:qa-deploy

#1151 [PWN-8105] [PWN-8106] Apply sort and filter for wormhole send tokens
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Extensions/Array+Wallet.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendFeeTokenService.swift
  p2p_wallet/Scenes/Main/Send/ChooseSendItem/Services/ChooseSendTokenService.swift
  p2p_wallet/Scenes/Main/Wormhole/ChooseWormholeSend/ChooseWormholeTokenService.swift
Labels: bug

#1153 [PWN-8120] Fix zero amount fiat string formation
  p2p_wallet/Extensions/Double+Extensions.swift
Labels: bug

#1159 [PWN-7466] Feature/pwn 7466 migrate some pod
  Podfile
  Podfile.lock
  p2p_wallet/SwiftUI/Lottie/LottieView.swift
  project.yml
Labels: no-qa

#1160 [PWN-7466] feat: refresh with taskgroup
  p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
Labels: no-qa

#1161 [PWN-7466] Naming for AccountDetail
  p2p_wallet/Coordinators/TabBar/HomeCoordinator.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsCoordinator.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsHistoryViewModel.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsView.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/AccountDetailsViewModel.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/Model/RendableAccountDetails+SolanaAccount.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/Model/RendableAccountDetails.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/Model/StandaloneRendableAccountDetail+Mock.swift
  p2p_wallet/Scenes/Main/WalletDetail/New/Model/StandaloneRendableAccountDetails+Mock.swift
Labels: no-qa

#1164 [PWN-7466] feat: unify assignWeak
  Packages/KeyAppKit/Sources/KeyAppBusiness/Ethereum/EthereumAccountsService.swift
  Packages/KeyAppKit/Sources/KeyAppBusiness/Solana/SolanaAccountsService.swift
  Packages/KeyAppKit/Sources/KeyAppKitCore/Common/Publisher+Extensions.swift
  Packages/KeyAppKit/Sources/KeyAppKitCore/Common/Publisher+assign.swift
  Podfile.lock
  p2p_wallet/Extensions/Combine/Publisher+asyncMap.swift
  p2p_wallet/Scenes/Main/NewHome/HomeViewModel.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/HomeAccountsViewModel.swift
  p2p_wallet/Scenes/Main/SupportedTokens/SupportedTokensViewModel.swift
  p2p_wallet/Scenes/Main/Wormhole/Claim/Fee/WormholeClaimFeeViewModel.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
Labels: no-qa

#1192 [PWN-8232] Handle self deallocation in ChooseItemView content
  p2p_wallet/Scenes/Main/Swap/ChooseSwapItem/ChooseSwapTokenCoordinator.swift
Labels: bug

#1194 [PWN-7466] Wormhole
  p2p_wallet/Coordinators/TabBar/TabBarCoordinator.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Aggregator/HomeAccountsAggregator.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/RendableAccount+EthereumAccount.swift
  p2p_wallet/Scenes/Main/NewHome/Subview/AccountList/Model/RenderableAccount.swift
  p2p_wallet/Scenes/Main/Wormhole/Send/WormholeSendInputViewModel.swift
Labels: auto:qa-deploy
